version: '3.7'

services:
  db:
    container_name: sqllite3
    image: nouchka/sqlite3:latest
    stdin_open: true
    restart: always
    tty: true
    env_file:
      - ./.env

      
  django:
    container_name: django
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/confi.d

volumes:
  pg_data:
  static_data:
